parameters:
    locale: 'en'

services:
    use_case.register_user:
        class: User\Application\UseCase\RegisterUserUseCase
        arguments:
            - '@repository.user'
            - '@encoder.password'

    use_case.get_user_profile:
        class: User\Application\UseCase\GetUserProfileUseCase
        arguments:
            - '@repository.user'

    use_case.get_user_token_view:
        class: User\Application\UseCase\GetUserTokenViewUseCase
        arguments:
            - '@lexik_jwt_authentication.encoder'

    use_case.user_follow_user:
        class: User\Application\UseCase\FollowUserUseCase
        arguments:
            - '@repository.user'

    use_case.user_unfollow_user:
        class: User\Application\UseCase\UnfollowUserUseCase
        arguments:
            - '@repository.user'

    use_case.update_user:
        class: User\Application\UseCase\UpdateUserUseCase
        arguments:
            - '@encoder.password'
            - '@repository.user'

    repository.user:
        class: User\Infrastructure\Doctrine\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - User\Application\Entity\User

    encoder.password:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        arguments:
            - 12

    controller.user.get_actions:
        class: User\Application\Controller\UserGetActionsController
        public: true
        arguments:
            - '@use_case.get_user_profile'
            - '@use_case.get_user_token_view'
            - '@security.token_storage'
            - '@serializer'

    controller.user.post_actions:
        class: User\Application\Controller\UserPostActionsController
        public: true
        arguments:
            - '@use_case.register_user'
            - '@use_case.get_user_token_view'
            - '@use_case.user_follow_user'
            - '@use_case.get_user_profile'
            - '@security.token_storage'
            - '@repository.user'
            - '@serializer'
            - '@encoder.password'

    controller.user.put_actions:
        class: User\Application\Controller\UserPutActionsController
        public: true
        arguments:
            - '@security.token_storage'
            - '@use_case.update_user'
            - '@use_case.get_user_token_view'
            - '@serializer'

    controller.user.delete_actions:
        class: User\Application\Controller\UserDeleteActionsController
        public: true
        arguments:
            - '@security.token_storage'
            - '@use_case.user_unfollow_user'
            - '@serializer'
            - '@use_case.get_user_profile'
            - '@repository.user'
