parameters:
    locale: 'en'

services:
    use_case.register_user:
        class: App\UseCase\RegisterUserUseCase
        public: true
        arguments:
            - '@repository.user'
            - '@encoder.password'

    use_case.get_user_profile:
        class: App\UseCase\GetUserProfileUseCase
        public: true
        arguments:
            - '@repository.user'

    use_case.user_follow_user:
        class: App\UseCase\FollowUserUseCase
        public: true
        arguments:
            - '@repository.user'

    use_case.user_unfollow_user:
        class: App\UseCase\UnfollowUserUseCase
        public: true
        arguments:
            - '@repository.user'

    repository.user:
        class: Infrastructure\Doctrine\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - App\Entity\User

    encoder.password:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        public: true
        arguments:
            - 12

    provider.user_token_view:
        class: App\Provider\UserTokenViewProvider
        public: true
        arguments:
            - '@lexik_jwt_authentication.encoder'
